version: '3.8'

services:
  vpn-server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: vpn-server
    ports:
      - "51820:51820/udp"  # WireGuard
      - "1194:1194/udp"    # OpenVPN
      - "8388:8388/tcp"    # Shadowsocks
      - "1080:1080/tcp"    # SOCKS5
      - "53:53/udp"        # DNS
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.disable_ipv6=1
    volumes:
      - ./server/configs:/etc/wireguard
      - ./server/configs:/etc/openvpn
      - ./server/logs:/var/log/vpn
    environment:
      - ENABLE_WIREGUARD=true
      - ENABLE_OPENVPN=true
      - ENABLE_SHADOWSOCKS=true
      - ENABLE_SOCKS5=true
      - ENABLE_DOH=true
    restart: unless-stopped

  vpn-client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: vpn-client
    cap_add:
      - NET_ADMIN
    volumes:
      - ./client/configs:/etc/vpn
    environment:
      - SERVER_HOST=vpn-server
      - SERVER_PORT=51820
      - PROTOCOL=auto
    depends_on:
      - vpn-server
    restart: unless-stopped